### ISSUE TITLE
Data.DList: Can't be safely imported

### ISSUE THREAD

**Issue by nponeccop** [leepike/Copilot#3]
I can't compile Copilot with ghc-7.8.3. I get an error during compilation of `copilot-core`:
```
src/Copilot/Core/External.hs:17:1:
    Data.DList: Can't be safely imported! The module itself isn't safe.
```

**Comment by leepike** [comment]
Thanks for the bug report. I fixed that bug, and made a number of other updates. It now should build on GHC 7.6 and 7.8. Pull and update the submodules. There's also a Travis build, too, linked to from the README.md.

**Comment by nponeccop** [comment]
I can confirm that current Hackage version `copilot-core-2.1.2` installs fine.
