### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by henrykmichalewski** [leepike/Copilot#5]
I ran into a compilation issue on Ubuntu 14.04, ghc version 7.6.3. 
```
    Preprocessing library copilot-language-2.1.2...
    target "base" is not a module name or a source file
```
The problem disappared and `make test` passed without errors once  in `lib/copilot-language/copilot-language.cabal` I removed
```    
     -fpackage-trust
     -- Trusted packages:
     -trust base
     -trust containers
     -trust array
```
Is it an acceptable "solution"? This issue is specific to this Linux and ghc versions - on other Linux versions the same code compiled without errors.

**Comment by leepike** [comment]
That's fine. Since 7.10 is released, I haven't really been trying to support 7.6.

**Comment by katyo** [comment]
Same problem on Debian Jessie too.
